global:
  scrape_interval: 5s
  scrape_timeout: 3s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: article-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - article-service-1:8080
          - article-service-2:8080
          - article-service-3:8080
        labels:
          service: article

  - job_name: comment-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - comment-service-1:8080
          - comment-service-2:8080
          - comment-service-3:8080
        labels:
          service: comment

  - job_name: subscriber-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - subscriber-service-1:8080
          - subscriber-service-2:8080
          - subscriber-service-3:8080
        labels:
          service: subscriber

  - job_name: newsletter-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - newsletter-service-1:8080
        labels:
          service: newsletter

  - job_name: publisher-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - publisher-service:8080
        labels:
          service: publisher
